### Test - Settlement Transfer:
POST http://localhost:1234/transfer
Content-Type: application/json
X-Correlation-ID: Manual-{{$uuid}}
authorization: 123456

#[USD.CAD.2023.1.26.13.33]
#[USD.2023.1.26.13.33]
# [settlementModel] is optional.
{
  "id" : null,
  "transferId" : "{{$uuid}}",
  "debitParticipantAccountId" : "{{$uuid}}",
  "creditParticipantAccountId" : "{{$uuid}}",
  "currencyCode" : "USD",
  "amount" : "10000",
  "timestamp" : {{$timestamp}}000,
  "settlementModel" :  "DEFAULT"
}

> {%
    client.global.set("txn_resp_id", response.body.settlementTransferId);
    client.global.set("txn_batch_id", response.body.batchId);
    client.global.set("txn_batch_identifier", response.body.batchIdentifier);
%}

### Test - Get Settlement Batches:
GET http://localhost:1234/settlement_batches?settlementModel=DEFAULT&fromDate=1674140933634&toDate={{$timestamp}}000
Content-Type: application/json
X-Correlation-ID: Manual-{{$uuid}}
authorization: 123456

### Test - Get Settlement Batch Accounts - By Batch Id:
GET http://localhost:1234/settlement_accounts?batchId={{txn_batch_id}}
Content-Type: application/json
X-Correlation-ID: Manual-{{$uuid}}
authorization: 123456

### Test - Get Settlement Batch Accounts - By Batch Identifier:
GET http://localhost:1234/settlement_accounts?batchIdentifier={{txn_batch_identifier}}
Content-Type: application/json
X-Correlation-ID: Manual-{{$uuid}}
authorization: 123456

### Test - Get Settlement Batch Transfers:
GET http://localhost:1234/settlement_transfers?batchId={{txn_batch_id}}
Content-Type: application/json
X-Correlation-ID: Manual-{{$uuid}}
authorization: 123456

### Test - Get Settlement Matrix Request:
GET http://localhost:1234/settlement_matrix_request?fromDate=1674140933634&toDate={{$timestamp}}000
Content-Type: application/json
X-Correlation-ID: Manual-{{$uuid}}
authorization: 123456

> {%
    client.global.set("matrix_req_id", response.body.id);
%}

### Test - Get Execute Settlement Matrix:
GET http://localhost:1234/execute_settlement_matrix?settlementMatrixReqId={{matrix_req_id}}
Content-Type: application/json
X-Correlation-ID: Manual-{{$uuid}}
authorization: 123456

