### Authorization by token, part 1. Retrieve and save token.
### Test - [Get settlement batches by id (incs seq)]:
GET http://localhost:3600/batches?settlementModel=DEFAULT&fromDate=1674140933634&toDate={{$timestamp}}000
Content-Type: application/json
X-Correlation-ID: Manual-{{$uuid}}
Authorization: Bearer {{access_token}}

### Test - [Get matrices by model]:
GET http://localhost:3600/matrices?model=DEFAULT&startDate=1674140933634&endDate={{$timestamp}}000
Content-Type: application/json
X-Correlation-ID: Manual-{{$uuid}}
Authorization: Bearer {{access_token}}
