@startuml

title Settlement from Central-Ledger

participant "Central-Ledger" as ext_cl
note over ext_cl
    Central-Ledger maintains
    liquidity balances
end note

box Settlements BC #F9FFF9
    participant "Rest API" as sbc_rest #D5E8D4
    participant "Event Handler" as sbc_event #D5E8D4
    note over sbc_event
        Kafka Topics
        - create Settlement Transfer
        - result of Settlement Transfer create
    end note
    participant "Settlements BC\nApp Logic" as sbc_app_logic #EDC54D
    database "Settlements-Database" as sbc_db #DAE8FC
end box

box Accounts & Balances BC #FFFFF9
    participant "A&B SVC" as abbc_grpc #D5E8D4
    database "A&B-Ledger" as abbc_tigerbeetle #DAE8FC
    note over abbc_grpc
        gRPC interface for
        Accounts & Balances
    end note
    note over abbc_tigerbeetle
        TigerBeetle 
        enabled/disabled
    end note
end box

box Auditing BC #E6E6E6
    participant "Auditing SVC" as audit_svc #D5E8D4
    database "Audit-Log" as audit_db #DAE8FC
end box

box Logging BC #E6E6E6
    participant "Logging SVC" as logging_svc #D5E8D4
    database "Logging-Database" as logging_db #DAE8FC
end box

box Security BC #E6E6E6
    participant "Security SVC" as security_svc #D5E8D4
    database "Security-Database" as security_db #DAE8FC
end box

group 1. Create Settlement Transfer - Central Ledger
autonumber
    ext_cl <--> ext_cl : **Transfer prepare**. \nObtain settlement model and allocation data\nvia Central-Ledger rules engine
    ext_cl <--> ext_cl : **Transfer fulfil**. \nAt this point, the transfer has cleared
    ext_cl -> sbc_event : \n//publishEvent// will all necessary data as\n**//ISettlementTransferDto//**
autonumber
    sbc_app_logic -> sbc_event : Listen for Settlement Transfer event
end

group 2. Settlement - App Logic
    sbc_app_logic <--> sbc_app_logic: Settlement Transfer event triggered
    sbc_app_logic --> sbc_app_logic : Validate Settlement Transfer data
    sbc_app_logic <--> sbc_db : Fetch & cache settlement config\n**Platform Config BC / Admin API**
    sbc_app_logic <--> sbc_db : **Obtain open batch** based on Settlement Transfer data.\n//Create new batch if no OPEN batch available//
    sbc_app_logic <-> abbc_grpc : Obtain **Settlement accounts** using Participant account
    abbc_grpc <--> abbc_tigerbeetle : Create account, if none exists
    abbc_grpc -> sbc_app_logic : Return **Account** creation info
    sbc_app_logic -> abbc_grpc: Create Settlement Transfer
    abbc_grpc <-> abbc_tigerbeetle: Create Transfer: update accounts \nto DR payer & CR payee
    abbc_grpc -> sbc_app_logic : Return **Transfer** creation info
    sbc_app_logic <-> sbc_app_logic: Prepare **Transfer/Account** response data
    sbc_app_logic -> sbc_event : Publish **Settlement Transfer** data
end

group 3. Settlement - Retrieve Batches
autonumber
    ext_cl -> sbc_rest : At time of fulfil:\n//retrieveSettlementBatches// \nINPUT:\n-> **From Date** - From\n-> **To Date** - To\n-> **Settlement Model** - Model //(optional)//\nOUTPUT:\n-> **Settlement Batches** - Batches
    sbc_rest -> sbc_app_logic : Request settlement batches
    sbc_app_logic -> abbc_grpc : Retrieve Settlement batch accounts
    abbc_grpc <-> abbc_tigerbeetle : Retrieve Settlement accounts & balances
    abbc_grpc -> sbc_app_logic : Return **Account** data
    sbc_app_logic --> sbc_app_logic : Prepare batch response data
    sbc_app_logic -> sbc_rest : Return **Batch** data
    sbc_rest -> ext_cl : Return **Batch** data
autonumber

end

@enduml
