@startuml
<style>
title {
  FontSize 24
}
</style>

skinparam defaultTextAlignment center
skinparam sequenceMessageAlign left

title Settlement from the Transfers BC

participant "vNext\nTransfers BC" as ext_transfers_bc


box Settlements BC #F9FFF9
'	participant "Settlements BC\n**Rest API**" as sbc_rest #D5E8D4
	participant "Settlements BC\n**Event Handler**" as sbc_event #D5E8D4
	participant "Settlements BC\n**Domain Logic**" as sbc_app_logic #EDC54D
	database "Settlements\n**Database**" as sbc_db #DAE8FC
end box

box Accounts & Balances BC #FFFFF9
    participant "A&B\nChart-of-Accounts\n**SVC**" as abbc_grpc #D5E8D4
    participant "A&B\nLedger **SVC**\nTigerBeetle / builtin" as abbc_tigerbeetle #DAE8FC
    note over abbc_grpc
        gRPC interface for 
        Accounts & Balances
    end note
    note over abbc_tigerbeetle
        TigerBeetle 
        enabled/disabled
    end note
end box

box Participants BC #eadddd
	participant "Participants\n**SVC**" as participants_svc #D5E8D4
end box

box Platform\nConfiguration\nBC #eee
	participant "Platform\n Configuration\n**SVC**" as platfconf_svc #D5E8D4
end box


group 1. Transfer completed - Transfers BC
autonumber
    ext_transfers_bc -> ext_transfers_bc : Transfer fulfil occurred
    ext_transfers_bc -> ext_transfers_bc : Include settlement model previously\nobtained using the //settlement-model-lib//\nduring the //transfer prepare// step
    ext_transfers_bc --> sbc_event : **TransferCommittedFulfiled** event is\npublished by the "Transfers BC" <&envelope-closed>
    sbc_event -> sbc_app_logic : Invoke\ndomain logic
end

group 2. Settlement - Domain Logic
autonumber
    sbc_app_logic -> sbc_app_logic : **Validate** transfer settlement data (including model)
    sbc_app_logic -> platfconf_svc : **Fetch** & cache settlements BC **configurations** from the Platform Configuration BC
    sbc_app_logic <-> sbc_db : **Determine batch** using Settlement Transfer data.\n//Create new batch if no OPEN batch available//
    sbc_app_logic <-> participants_svc : Obtain **Settlement accounts** from the Participant Accounts list
    sbc_app_logic -> abbc_grpc : Create batch and participant settlement accounts, if non-existing
    abbc_grpc -> abbc_tigerbeetle : Create accounts,if non-existing\n(internal A&B call)
    sbc_app_logic -> abbc_grpc: Create Settlement entries (DR payer & CR payee)
    abbc_grpc -> abbc_tigerbeetle: Create Settlement entries\n(internal A&B call)
    sbc_app_logic -> sbc_db: Update settlement batch state
end

@enduml
