@startuml
<style>
title {
  FontSize 24
}
</style>

skinparam defaultTextAlignment center
skinparam sequenceMessageAlign left

title Creation of Settlement Matrix from vNext Participants BC


participant "vNext UI / API" as ext_transfers_bc

box Settlements BC #F9FFF9
	participant "Settlements BC\n**Rest API**" as sbc_rest #D5E8D4
	participant "Settlements BC\n**Event Handler**" as sbc_event #D5E8D4
	participant "Settlements BC\n**Domain Logic**" as sbc_app_logic #EDC54D
	database "Settlements\n**Database**" as sbc_db #DAE8FC
end box

box Accounts and Balances BC #FFFFF9
    participant "A&B\nChart-of-Accounts\n**SVC**" as abbc_grpc #D5E8D4
    participant "A&B\nLedger **SVC**\nTigerBeetle / builtin" as abbc_tigerbeetle #DAE8FC
    note over abbc_grpc
        Exposed gRPC interface for
        Accounts & Balances.
    end note
    note over abbc_tigerbeetle
		TigerBeetle
		enabled/disabled
    end note
end box

group 1. Trigger Settlement Matrix - Admin API
autonumber
    ext_transfers_bc -> sbc_rest : Request settlement matrix generation \nIncluding filtering criteria
	sbc_rest --> sbc_event: RequestMatrixGeneration event
	sbc_rest -> ext_transfers_bc : response with future matrix id (async)
    sbc_event -> sbc_app_logic : Invoke\ndomain logic
end

group 2. Settlement Matrix - Initial Generation
autonumber
    sbc_app_logic -> sbc_app_logic : Create initial state of Matrix, Including Criteria \n(**From Date** - From -> **To Date** - To\n-> **Settlement Model** - Model)
    sbc_app_logic -> sbc_db : Fetch all batches that form part of the settlement criteria

    sbc_app_logic -> abbc_grpc : Obtain Debit/Credit **Settlement Accounts** based on batches\nSingle bulk/array call
    abbc_grpc -> abbc_tigerbeetle: Fetch **Batch Accounts**
    abbc_grpc -> sbc_app_logic : Return **Batch Accounts** based on batches
    sbc_app_logic -> sbc_app_logic : Prepare the Settlement Matrix
    sbc_app_logic -> sbc_db : Persist the Settlement Matrix
    sbc_app_logic --> ext_transfers_bc : Publish SettlementMatrixGeneratedEvent
end

@enduml
