@startuml

title Settlement Matrix - Refer to Reference Architecture: [https://miro.com/app/board/o9J_lJyA1TA=/]

box External-Transfer-System #FFFFF9
    participant "Central-Ledger" as ext_cl
    participant "Transfer-BC" as ext_transfers_bc
end box

box Settlements BC #F9FFF9
	participant "Rest API" as sbc_rest #D5E8D4
	participant "Settlements BC\nApp Logic" as sbc_app_logic #EDC54D
	database "Settlements-Database" as sbc_db #DAE8FC
end box

box Accounts and Balances BC #FFFFF9
    participant "gRPC" as abbc_grpc #D5E8D4
    participant "TigerBeetle" as abbc_tigerbeetle #D5E8D4
    note over abbc_grpc
        Exposed interface for
        Accounts and Balances.
    end note
    note over abbc_tigerbeetle
        TigerBeetle may be turned off/on.
    end note
end box

group 1. Trigger Settlement Matrix - Central Ledger / Admin API
autonumber
    ext_cl -> sbc_rest : Request settlement matrix
autonumber
    ext_transfers_bc -> sbc_rest : **OR** \nRequest settlement matrix
    sbc_rest -> sbc_app_logic : Invoke the App layer
end

group 2. Settlement - App Logic
autonumber
    sbc_app_logic <--> sbc_app_logic: Settlement Matrix triggered with:\n-> **From Date** - From\n-> **To Date** - To\n-> **Settlement Model** - Model
    sbc_app_logic --> sbc_app_logic : Validate **settlement transfer data payload**
    sbc_app_logic <--> sbc_db : Fetch and cache settlement configuration\n**TODO - This needs to be updated**
    sbc_app_logic <--> sbc_db : Obtain current open settlement batch based on \n**settlement transfer data payload**\n//New OPEN Batch will be created if no OPEN batch is available//
    sbc_app_logic <-> abbc_grpc : Obtain Debit/Credit **Settlement Accounts** based on participant account info\n//(The settlement accounts are derived and linked from the participant accounts)//
    abbc_grpc <--> abbc_tigerbeetle : Create account \nif 'not exists'
    abbc_grpc -> sbc_app_logic : Return **Account** creation info
    sbc_app_logic -> abbc_grpc: Create Settlement Transfer
    abbc_grpc <-> abbc_tigerbeetle: Debit Payer, Credit Payee
    abbc_grpc -> sbc_app_logic : Return **Transfer** creation info
    sbc_app_logic <--> sbc_app_logic: Return **Transfer/Account** info based on: \n-> REST - Account balance info\n-> gRPC - Account balance info\n-> Event - Publish Event
end

@enduml
