@startuml

title Static Settlement Matrix

participant "Admin API" as ext_transfers_bc

box Settlements BC #F9FFF9
	participant "Rest API" as sbc_rest #D5E8D4
	participant "Settlements BC\nApp Logic" as sbc_app_logic #EDC54D
	database "Settlements-Database" as sbc_db #DAE8FC
end box

box Accounts and Balances BC #FFFFF9
    participant "A&B SVC" as abbc_grpc #D5E8D4
    database "A&B-Ledger" as abbc_tigerbeetle #DAE8FC
    note over abbc_grpc
        Exposed gRPC interface for
        Accounts & Balances.
    end note
    note over abbc_tigerbeetle
        TigerBeetle may be turned off/on.
    end note
end box

group 1. Trigger Settlement Matrix - Admin API
autonumber
    ext_transfers_bc -> sbc_rest : **Settlement Matrix** - //STATIC//\n(batchId list)
    sbc_rest -> sbc_app_logic : Invoke the App layer
end

group 2. Settlement - App Logic
autonumber
    sbc_app_logic <--> sbc_app_logic: Settlement Matrix triggered with:\n-> **Batch ID** - List of existing batch id's
    sbc_app_logic <--> sbc_db : Fetch all batches via provided batchId's

    sbc_app_logic <-> abbc_grpc : Obtain Debit/Credit **Settlement Accounts** based on batches
    abbc_grpc <-> abbc_tigerbeetle: Fetch **Settlement Accounts**
    abbc_grpc <-> sbc_app_logic : Return **Settlement Accounts** based on batches
    sbc_app_logic <--> sbc_app_logic : Prepare the Settlement Matrix
    sbc_app_logic -> sbc_rest : Return Settlement Matrix
    sbc_rest -> ext_transfers_bc : Matrix id returned in response
end

@enduml
