@startuml

object ITransferDto
    ITransferDto : **//(PK)// id** = //uuid//
    ITransferDto : **transferId** = //uuid//
    ITransferDto : ...
object ISettlementBatchAccount
    ISettlementBatchAccount : **//(PK)// id** = //uuid//
    ISettlementBatchAccount : **accountExtId** = //uuid - A&B//
    ISettlementBatchAccount : **participantId** = //uuid - Participants//
    ISettlementBatchAccount : ...
object ISettlementBatch
    ISettlementBatch : **//(PK)// id** = //uuid//
    ISettlementBatch : ...

ISettlementBatchAccount <|-- ITransferDto : //debitAccount//
ISettlementBatchAccount <|-- ITransferDto : //creditAccount//
ISettlementBatch <|-- ITransferDto : //batch (assigned during transfer) **[*..1]**//
ISettlementBatch <|-- ISettlementBatchAccount : //batch **[*..1]**//

@enduml
