@startuml

object ISettlementMatrix
    ISettlementMatrix : **//(PK)// id** = //uuid//
    ISettlementMatrix : **batches** = //uuid - Batches//
    ISettlementMatrix : ...
object ITransferDto
    ITransferDto : **//(PK)// id** = //uuid//
    ITransferDto : **transferId** = //uuid//
    ITransferDto : **debitAccount** = //uuid//
    ITransferDto : **creditAccount** = //uuid//
    ITransferDto : ...
object ISettlementBatchAccount
    ISettlementBatchAccount : **//(PK)// id** = //uuid//
    ISettlementBatchAccount : **accountExtId** = //uuid - A&B//
    ISettlementBatchAccount : **participantId** = //uuid - Participants//
    ISettlementBatchAccount : ...
object ISettlementBatch
    ISettlementBatch : **//(PK)// id** = //uuid//
    ISettlementBatch : ...
object IAwaitingSettlement
    IAwaitingSettlement : **//(PK)// id** = //uuid//
    IAwaitingSettlement : **matrix** = //uuid - Settlement Matrix//
    IAwaitingSettlement : **batch** = //uuid - Settlement Matrix Batch//

ISettlementBatchAccount <|-- ITransferDto : //debitAccount//
ISettlementBatchAccount <|-- ITransferDto : //creditAccount//
ISettlementBatch <|-- ITransferDto : //batch (assigned during transfer) **[*..1]**//
ISettlementBatch <|-- ISettlementBatchAccount : //batch **[*..1]**//

ISettlementBatch <|-- IAwaitingSettlement : //batch **[1..*]**//
ISettlementMatrix <|-- IAwaitingSettlement : //matrix **[1..1]**//
ISettlementBatch <|-- ISettlementMatrix : //matrix **[1..*]**//

@enduml
