@startmindmap
+[#Orange] **Settlements-BC**
++[#Lightblue] Database
+++_ MongoDB
+++_ Mock (//Testing Purposes//)
++[#Lightblue] Kafka
+++_ //public-messages-lib//
++[#Orange] Auditing-BC
+++[#Lightblue] Kafka
++++_ //public-messages-lib//
++[#Orange] Logging-BC
+++[#Lightblue] Kafka
++++_ //public-messages-lib//
++[#Orange] Security-BC
+++[#Lightblue] Kafka
++++_ //public-messages-lib//
++[#LightGreen] Ledger Adapter
+++[#Orange] Accounts & Balances
****_ TigerBeetle
***_ Mock (//Testing Purposes//)
--[#Orange] Transfers-BC
---[#Lightblue] Kafka
----_ //public-messages-lib//
--[#Orange] Participants-BC
---[#Lightblue] Kafka
----_ //public-messages-lib//

legend left
**Orange** = vNext
**Blue** = 3rd Party Components
**Green** = Settlement Components (Features)
**//public-messages-lib//** = Core MJL library
endlegend

@endmindmap